"""HxGraph — Report and export generation.

Produces graphify-equivalent outputs:
  graph_report()  → GRAPH_REPORT.md markdown (same format you know from graphify)
  graph_export()  → graph.json (nodes + edges as JSON — feeds the HTML visualizer)
  graph_html()    → interactive D3.js graph.html
"""
from __future__ import annotations

import json
from collections import defaultdict
from datetime import datetime, timezone

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from case_service.db.models import GraphNodeModel, GraphEdgeModel
from case_service.hxgraph.community import detect_communities, community_hubs


async def _fetch_visible(
    session: AsyncSession, tenant_id: str | None,
) -> tuple[list[GraphNodeModel], list[GraphEdgeModel]]:
    """All nodes/edges visible to this caller (see query._vis_clause).

    Edges are kept only when BOTH endpoints are visible, so an export can't
    leak a hidden node's id through an edge reference.
    """
    from case_service.hxgraph.query import _vis_clause
    nodes = (await session.execute(
        select(GraphNodeModel).where(_vis_clause(tenant_id))
    )).scalars().all()
    edges = (await session.execute(select(GraphEdgeModel))).scalars().all()
    if tenant_id is not None:
        visible_ids = {n.id for n in nodes}
        edges = [e for e in edges
                 if e.from_node_id in visible_ids and e.to_node_id in visible_ids]
    return list(nodes), list(edges)


# ── Graph Report (graphify GRAPH_REPORT.md equivalent) ───────────────────────

async def graph_report(session: AsyncSession, tenant_id: str | None = None) -> str:
    nodes, edges = await _fetch_visible(session, tenant_id)

    node_ids = [str(n.id) for n in nodes]
    edge_pairs = [(str(e.from_node_id), str(e.to_node_id)) for e in edges]

    # Degree map
    degree: dict[str, int] = defaultdict(int)
    for a, b in edge_pairs:
        degree[a] += 1
        degree[b] += 1

    # Community detection
    community_map = detect_communities(node_ids, edge_pairs)

    # Update community_id on nodes (in-memory for report, not persisted here)
    id_to_node = {str(n.id): n for n in nodes}
    for nid, cid in community_map.items():
        if nid in id_to_node:
            id_to_node[nid].community_id = cid

    hubs = community_hubs(community_map, degree)
    communities: dict[int, list[GraphNodeModel]] = defaultdict(list)
    for nid, cid in community_map.items():
        if nid in id_to_node:
            communities[cid].append(id_to_node[nid])

    # Edge type breakdown
    edge_type_counts: dict[str, int] = defaultdict(int)
    for e in edges:
        edge_type_counts[e.edge_type] += 1

    # Node type breakdown
    node_type_counts: dict[str, int] = defaultdict(int)
    for n in nodes:
        node_type_counts[n.node_type] += 1

    structural_edges = sum(v for k, v in edge_type_counts.items() if k != "similar_to")
    semantic_edges   = edge_type_counts.get("similar_to", 0)

    now = datetime.now(timezone.utc).strftime("%Y-%m-%d")

    lines = [
        f"# HxGraph Report — HELIX  ({now})",
        "",
        "## Summary",
        f"- {len(nodes)} nodes · {len(edges)} edges · {len(communities)} communities detected",
        f"- Structural edges: {structural_edges} · Semantic (similar_to) edges: {semantic_edges}",
        f"- Node types: {', '.join(f'{v} {k}' for k, v in sorted(node_type_counts.items()))}",
        "",
        "## Edge Types",
    ]
    for etype, count in sorted(edge_type_counts.items(), key=lambda x: -x[1]):
        lines.append(f"- `{etype}`: {count}")

    lines += [
        "",
        "## Community Hubs (Navigation)",
        "_Each community is a cluster of related platform concepts._",
        "",
    ]

    for cid in sorted(communities.keys()):
        members = communities[cid]
        hub_ids = hubs.get(cid, [])
        hub_nodes = [id_to_node[nid] for nid in hub_ids if nid in id_to_node]
        hub_labels = [f"`{n.node_type}:{n.label}`" for n in hub_nodes]

        type_summary = ", ".join(
            f"{v} {k}" for k, v in
            sorted(defaultdict(int, {n.node_type: 0 for n in members}).items())
        )
        # Actual type counts for this community
        tc: dict[str, int] = defaultdict(int)
        for n in members:
            tc[n.node_type] += 1
        type_summary = ", ".join(f"{v} {k}" for k, v in sorted(tc.items()))

        lines.append(f"### Community {cid} — {len(members)} nodes ({type_summary})")
        if hub_labels:
            lines.append(f"**Hubs:** {', '.join(hub_labels)}")
        lines.append("")

    lines += [
        "## Highest-Degree Nodes (Most Connected)",
        "",
    ]
    top_nodes = sorted(nodes, key=lambda n: degree.get(str(n.id), 0), reverse=True)[:15]
    for n in top_nodes:
        d = degree.get(str(n.id), 0)
        lines.append(f"- **{n.label}** (`{n.node_type}`) — degree {d}")

    lines += [
        "",
        "---",
        "_Generated by HxGraph — the Velaris native knowledge graph._",
        "_Query via: `POST /api/v1/graph/query`, `GET /api/v1/graph/path`, `GET /api/v1/graph/explain`_",
    ]

    return "\n".join(lines)


# ── JSON Export (graph.json equivalent) ──────────────────────────────────────

async def graph_export(session: AsyncSession, tenant_id: str | None = None) -> dict:
    nodes, edges = await _fetch_visible(session, tenant_id)

    return {
        "meta": {
            "generated_at": datetime.now(timezone.utc).isoformat(),
            "node_count": len(nodes),
            "edge_count": len(edges),
        },
        "nodes": [
            {
                "id": str(n.id),
                "node_type": n.node_type,
                "name": n.name,
                "label": n.label,
                "summary": n.summary,
                "community_id": n.community_id,
                "properties": n.properties or {},
                "source": n.source,
            }
            for n in nodes
        ],
        "edges": [
            {
                "id": str(e.id),
                "from": str(e.from_node_id),
                "to": str(e.to_node_id),
                "edge_type": e.edge_type,
                "weight": e.weight,
            }
            for e in edges
        ],
    }


# ── HTML Visualizer (graph.html equivalent — D3.js force-directed) ────────────

async def graph_html(session: AsyncSession, tenant_id: str | None = None) -> str:
    data = await graph_export(session, tenant_id)
    data_json = json.dumps(data)

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>HxGraph — HELIX Knowledge Graph</title>
<style>
  body {{ margin: 0; background: #0f1117; font-family: system-ui, sans-serif; color: #e2e8f0; }}
  #toolbar {{ position: fixed; top: 0; left: 0; right: 0; height: 48px; background: #1a1d2e;
              border-bottom: 1px solid #2d3748; display: flex; align-items: center; gap: 16px;
              padding: 0 20px; z-index: 10; }}
  #toolbar h1 {{ font-size: 15px; font-weight: 700; color: #818cf8; margin: 0; }}
  #toolbar input {{ padding: 5px 10px; border-radius: 6px; border: 1px solid #4a5568;
                   background: #0f1117; color: #e2e8f0; font-size: 12px; width: 220px; }}
  #toolbar select {{ padding: 5px 8px; border-radius: 6px; border: 1px solid #4a5568;
                    background: #0f1117; color: #e2e8f0; font-size: 12px; }}
  #stats {{ margin-left: auto; font-size: 11px; color: #718096; }}
  #canvas {{ position: fixed; top: 48px; left: 0; right: 0; bottom: 0; }}
  #tooltip {{ position: fixed; background: #1a1d2e; border: 1px solid #4a5568; border-radius: 8px;
             padding: 10px 14px; font-size: 12px; pointer-events: none; display: none;
             max-width: 280px; z-index: 20; line-height: 1.5; }}
  .type-tag {{ display: inline-block; padding: 1px 6px; border-radius: 4px; font-size: 10px;
               font-weight: 700; text-transform: uppercase; margin-bottom: 4px; }}
</style>
</head>
<body>
<div id="toolbar">
  <h1>⬡ HxGraph</h1>
  <input id="search" placeholder="Search nodes…" />
  <select id="typeFilter"><option value="">All types</option></select>
  <div id="stats"></div>
</div>
<svg id="canvas"></svg>
<div id="tooltip"></div>

<script src="https://d3js.org/d3.v7.min.js"></script>
<script>
const RAW = {data_json};

const NODE_COLORS = {{
  case_type: "#818cf8", stage: "#34d399", step: "#60a5fa", form: "#f59e0b",
  field: "#fb923c", module: "#a78bfa", endpoint: "#94a3b8", access_group: "#f472b6",
  connector: "#2dd4bf", concept: "#e879f9", pattern: "#fbbf24",
}};

let nodes = RAW.nodes.map(n => ({{...n}}));
let links = RAW.edges.map(e => ({{...e, source: e.from, target: e.to}}));

// Populate type filter
const types = [...new Set(nodes.map(n => n.node_type))].sort();
const sel = document.getElementById("typeFilter");
types.forEach(t => {{ const o = document.createElement("option"); o.value = t; o.textContent = t; sel.appendChild(o); }});

document.getElementById("stats").textContent =
  `${{nodes.length}} nodes · ${{links.length}} edges`;

const svg = d3.select("#canvas");
const w = window.innerWidth, h = window.innerHeight - 48;
svg.attr("width", w).attr("height", h);
const g = svg.append("g");

svg.call(d3.zoom().scaleExtent([0.05, 4]).on("zoom", e => g.attr("transform", e.transform)));

const sim = d3.forceSimulation(nodes)
  .force("link", d3.forceLink(links).id(d => d.id).distance(d => d.edge_type === "similar_to" ? 120 : 60).strength(0.4))
  .force("charge", d3.forceManyBody().strength(-180))
  .force("center", d3.forceCenter(w / 2, h / 2))
  .force("collision", d3.forceCollide(18));

const link = g.append("g").selectAll("line").data(links).join("line")
  .attr("stroke", d => d.edge_type === "similar_to" ? "#4a5568" : "#2d3748")
  .attr("stroke-width", d => d.edge_type === "similar_to" ? 0.5 : 1.2)
  .attr("stroke-dasharray", d => d.edge_type === "similar_to" ? "3,3" : null)
  .attr("opacity", 0.6);

const node = g.append("g").selectAll("circle").data(nodes).join("circle")
  .attr("r", d => d.node_type === "case_type" ? 10 : d.node_type === "module" ? 8 : 5)
  .attr("fill", d => NODE_COLORS[d.node_type] || "#718096")
  .attr("stroke", "#0f1117").attr("stroke-width", 1.5)
  .call(d3.drag()
    .on("start", (e, d) => {{ if (!e.active) sim.alphaTarget(0.3).restart(); d.fx = d.x; d.fy = d.y; }})
    .on("drag",  (e, d) => {{ d.fx = e.x; d.fy = e.y; }})
    .on("end",   (e, d) => {{ if (!e.active) sim.alphaTarget(0); d.fx = null; d.fy = null; }}));

const label = g.append("g").selectAll("text").data(nodes).join("text")
  .text(d => d.label.length > 22 ? d.label.slice(0, 22) + "…" : d.label)
  .attr("font-size", 9).attr("fill", "#94a3b8").attr("dx", 8).attr("dy", 4);

const tip = document.getElementById("tooltip");
node.on("mouseover", (e, d) => {{
  tip.style.display = "block";
  tip.style.left = (e.clientX + 12) + "px";
  tip.style.top  = (e.clientY - 10) + "px";
  const color = NODE_COLORS[d.node_type] || "#718096";
  tip.innerHTML = `<span class="type-tag" style="background:${{color}}22;color:${{color}}">${{d.node_type}}</span><br>
    <strong>${{d.label}}</strong><br>${{d.summary || ""}}`;
}}).on("mousemove", (e) => {{
  tip.style.left = (e.clientX + 12) + "px";
  tip.style.top  = (e.clientY - 10) + "px";
}}).on("mouseout", () => {{ tip.style.display = "none"; }});

sim.on("tick", () => {{
  link.attr("x1", d => d.source.x).attr("y1", d => d.source.y)
      .attr("x2", d => d.target.x).attr("y2", d => d.target.y);
  node.attr("cx", d => d.x).attr("cy", d => d.y);
  label.attr("x", d => d.x).attr("y", d => d.y);
}});

// Search
document.getElementById("search").addEventListener("input", e => {{
  const q = e.target.value.toLowerCase();
  node.attr("opacity", d => !q || d.label.toLowerCase().includes(q) ? 1 : 0.1);
  label.attr("opacity", d => !q || d.label.toLowerCase().includes(q) ? 1 : 0.05);
}});

// Type filter
sel.addEventListener("change", e => {{
  const t = e.target.value;
  node.attr("opacity", d => !t || d.node_type === t ? 1 : 0.08);
  label.attr("opacity", d => !t || d.node_type === t ? 1 : 0.02);
}});
</script>
</body>
</html>"""
