-- ============================================================================
-- Velaris — MySQL bpm_concepts parity seed (DB SDK Phase 1b). GENERATED — DO NOT
-- EDIT BY HAND; regenerate via scripts/gen_mysql_bpm_seed.py from the Postgres
-- migration 040 and hand-review the diff.
--
-- Advisory reference data for the HxMigrate BPM importer (cosmetic parity — the
-- importer degrades gracefully without it). The table has no unique key, so this is
-- one idempotent INSERT…SELECT guarded by WHERE NOT EXISTS (re-applying is a no-op).
-- ============================================================================

INSERT INTO bpm_concepts
  (id, source_tool, source_concept, helix_equiv, helix_node_type,
   description, example, confidence, notes, created_at)
SELECT UUID(), t.c1, t.c2, t.c3, t.c4, t.c5, t.c6, t.c7, t.c8, NOW()
FROM (
  SELECT 'pega' AS c1, 'Case Type' AS c2, 'case_type' AS c3, 'case_type' AS c4, 'The top-level container for a business process. Defines the lifecycle, stages, and data model.' AS c5, 'InsuranceClaim → case_type: insurance_claim' AS c6, 'exact' AS c7, NULL AS c8
  UNION ALL SELECT 'pega', 'Stage',             'stage',             'stage',         'A named phase within a case lifecycle. Cases move from stage to stage as work progresses.',               'Intake stage → stage: intake',                          'exact',   NULL
  UNION ALL SELECT 'pega', 'Assignment shape',  'user_task step',    'step',          'Work assigned to a human operator. The operator opens it, acts on it, and submits.',                     'ReviewAssignment → user_task step: review',             'exact',   NULL
  UNION ALL SELECT 'pega', 'Approval shape',    'approval step',     'step',          'A yes/no decision point. Approver sees context and approves or rejects.',                                'ManagerApproval → approval step',                       'exact',   NULL
  UNION ALL SELECT 'pega', 'Decision shape',    'routing rule',      NULL,            'Conditional branching based on case data. Routes to different stages or steps.',                         'CreditCheck decision → routing rule with conditions',   'close',   'Complex multi-branch decisions may need manual review'
  UNION ALL SELECT 'pega', 'Data Transform',    'automated step',    'step',          'Automated field mapping and data manipulation. Runs without human input.',                               'MapClaimData → automated step',                         'close',   'Logic must be re-expressed as Helix field mappings'
  UNION ALL SELECT 'pega', 'Subprocess',        'embedded stage',    'stage',         'A reusable child process embedded in a parent case.',                                                   'DocumentVerification subprocess → embedded stage',      'close',   'Helix uses HxFusion (P47) for full subprocess support'
  UNION ALL SELECT 'pega', 'Spin-off case',     'child case',        'case_type',     'Creates a new case instance from within a running case.',                                               'SpinOffPayment → child case_type: payment',             'close',   NULL
  UNION ALL SELECT 'pega', 'Section',           'form section',      'form',          'A named group of fields in a Pega form. Maps directly to a FormDefinition section.',                   'ClaimantSection → section in Claim Form',               'exact',   NULL
  UNION ALL SELECT 'pega', 'Property',          'form field',        'field',         'A single data field. Maps to a field in a FormDefinition section.',                                    'claimAmount property → currency field: claim_amount',   'exact',   NULL
  UNION ALL SELECT 'pega', 'Flow Action',       'form step',         'step',          'A button or action on a screen that captures input and advances the flow.',                            'SubmitClaim flow action → user_task step with form',    'exact',   NULL
  UNION ALL SELECT 'pega', 'Harness',           'portal page',       NULL,            'The full-page UI container. Helix uses Portal.tsx for customer-facing and Studio for operators.',       'WorkHarness → Studio CaseManager module',               'close',   'UI layout is not converted — rebuilt in React'
  UNION ALL SELECT 'pega', 'Clipboard',         'case data (JSONB)', NULL,            'In-memory data model for a running case. In Helix, case data lives in case_instances.data JSONB.',     'pyWorkPage.ClaimAmount → case.data.claim_amount',       'close',   NULL
  UNION ALL SELECT 'pega', 'Data Page',         'API endpoint',      'endpoint',      'Cached data source. In Helix, data is fetched from API endpoints with caching at the HTTP layer.',     'D_ClaimList data page → GET /api/v1/cases endpoint',   'partial', 'Caching strategy differs'
  UNION ALL SELECT 'pega', 'Access Group',      'access_group',      'access_group',  'Groups operators and defines what they can see and do. Direct equivalent in Helix.',                  'ClaimsAdjusters → access_group: claims_adjusters',     'exact',   NULL
  UNION ALL SELECT 'pega', 'Operator',          'operator / user',   NULL,            'A person who uses the Pega application. Maps to Helix operator with access group memberships.',       'adjuster@example.com → operator in Claims Adjusters',  'exact',   NULL
  UNION ALL SELECT 'pega', 'Worklist',          'Work Center queue', NULL,            'Personal queue of assignments for an operator. Helix equivalent is the Work Center module.',          'Worklist → /work-center',                               'exact',   NULL
  UNION ALL SELECT 'pega', 'Work Queue',        'queue',             NULL,            'Shared queue that multiple operators can pull from. Helix queues are defined per access group.',       'ClaimsQueue → queue in Claims Adjusters access group',  'exact',   NULL
  UNION ALL SELECT 'pega', 'Role',              'access_role',       NULL,            'Named set of privileges. Roles are assigned to access groups in both Pega and Helix.',               'AdjusterRole → access_role with claim_update privilege', 'exact',  NULL
  UNION ALL SELECT 'pega', 'Service Level',     'sla_rule',          NULL,            'Defines goal, deadline, and passed-deadline (breach) timers. Direct equivalent in Helix.',            'ClaimSLA → sla_rule with 24h deadline',                 'exact',   NULL
  UNION ALL SELECT 'pega', 'Urgency',           'priority',          NULL,            'Numeric urgency in Pega maps to priority levels in Helix (low/medium/high/critical).',               'Urgency 50 → priority: high',                           'close',   'Pega uses 0-100 scale; Helix uses named tiers'
  UNION ALL SELECT 'pega', 'Connector',         'HxConnect connector', 'connector',   'Integration with an external system. Maps to a HxConnect ConnectorProtocol implementation.',         'SalesforceConnector → HxConnect Salesforce adapter',   'close',   'Connector logic must be re-implemented in HxConnect'
  UNION ALL SELECT 'pega', 'Correspondence',    'email template',    NULL,            'Outbound email template. Maps to Helix email templates (P25).',                                       'ClaimConfirmation → email template: claim_confirmation', 'exact',  NULL
  UNION ALL SELECT 'pega', 'Decision Table',    'routing rule',      NULL,            'Tabular IF/THEN logic. Converted to Helix conditional routing rules.',                               'PremiumCalc table → routing rule with conditions',      'close',   'Complex tables may need manual conversion'
  UNION ALL SELECT 'pega', 'Ruleset',           'case_type version', NULL,            'A versioned container of rules. Maps to case_type version + migration file.',                        'InsuranceRuleset 01-01-01 → case_type v1.0 + migration', 'close',  NULL
  UNION ALL SELECT 'pega', 'Portal',            'portal',            NULL,            'Customer-facing or staff-facing UI portal. Direct equivalent in Helix.',                             'CustomerPortal → portal: customer',                     'exact',   NULL
  UNION ALL SELECT 'camunda', 'Process Definition',  'case_type',         'case_type',  'The top-level BPMN process. Maps to a Helix case_type with stages derived from swim lanes or logical groups.', 'LoanProcess.bpmn → case_type: loan_application',      'close',   'BPMN flow is more rigid than Helix stages; restructuring required'
  UNION ALL SELECT 'camunda', 'UserTask',            'user_task step',    'step',       'Human task requiring operator input. Direct equivalent.',                                                        'ReviewTask → user_task step: review',                 'exact',   NULL
  UNION ALL SELECT 'camunda', 'ServiceTask',         'automated step',    'step',       'Automated task calling a service. Maps to Helix automated step or HxConnect connector call.',                   'PaymentServiceTask → automated step + connector',     'close',   'Java delegate logic must be re-implemented'
  UNION ALL SELECT 'camunda', 'StartEvent',          'case creation',     NULL,         'Marks the beginning of a process. Maps to case instantiation in Helix.',                                        'StartEvent → case created via portal or API',         'exact',   NULL
  UNION ALL SELECT 'camunda', 'EndEvent',            'case resolution',   NULL,         'Marks process completion. Maps to case status = resolved/closed.',                                               'EndEvent → case.status = resolved',                   'exact',   NULL
  UNION ALL SELECT 'camunda', 'ExclusiveGateway',    'routing rule',      NULL,         'XOR decision — one path taken. Maps to conditional routing in Helix.',                                          'ApprovalGateway → routing rule: if approved → next',  'close',   NULL
  UNION ALL SELECT 'camunda', 'ParallelGateway',     'parallel stages',   NULL,         'AND split/join — multiple paths run simultaneously. Helix handles with parallel stages.',                       'ParallelGateway → two stages running concurrently',   'partial', 'Full parallel execution needs HxFusion (P47)'
  UNION ALL SELECT 'camunda', 'CallActivity',        'child case',        'case_type',  'Calls a reusable sub-process. Maps to spawning a child case in Helix.',                                         'DocumentVerification call → child case_type',         'close',   NULL
  UNION ALL SELECT 'camunda', 'BoundaryEvent (timer)', 'sla_rule',        NULL,         'Timer boundary on a task maps to a Helix SLA rule with escalation.',                                            'TimerBoundary 48h → sla_rule deadline 48h',           'close',   NULL
  UNION ALL SELECT 'camunda', 'MessageEvent',        'notification',      NULL,         'Send/receive message maps to Helix email (P25) or push notification (P27).',                                    'MessageEnd → email notification to customer',         'close',   NULL
  UNION ALL SELECT 'camunda', 'ScriptTask',          'automated step',    'step',       'Inline script execution. Logic must be re-expressed as Helix automated step.',                                   'GroovyScript → automated step',                       'partial', 'Script logic requires manual migration'
  UNION ALL SELECT 'camunda', 'BusinessRuleTask',    'routing rule',      NULL,         'DMN decision table evaluation. Maps to Helix routing rules.',                                                    'DMNTask → routing rule with conditions',              'close',   NULL
  UNION ALL SELECT 'camunda', 'Subprocess',          'embedded stage',    'stage',      'Embedded sub-process. Maps to a sub-stage group in Helix.',                                                     'InlineSubprocess → embedded stage group',             'close',   'Full subprocess support in HxFusion (P47)'
  UNION ALL SELECT 'camunda', 'SequenceFlow',        'stage transition',  NULL,         'Arrow connecting elements. Maps to stage/step ordering in Helix definition_json.',                              'SequenceFlow A→B → stage order + step order',         'exact',   NULL
  UNION ALL SELECT 'appian', 'Process Model',        'case_type',         'case_type',  'Top-level Appian process. Maps to a Helix case_type.',                                                          'LoanApprovalProcess → case_type: loan_approval',      'close',   NULL
  UNION ALL SELECT 'appian', 'User Input Task',      'user_task step',    'step',       'Human task in Appian. Direct equivalent to Helix user_task step.',                                              'ReviewApplicationTask → user_task step',              'exact',   NULL
  UNION ALL SELECT 'appian', 'Automated Task',       'automated step',    'step',       'System-executed task. Maps to Helix automated step.',                                                            'SendEmailTask → automated step',                      'exact',   NULL
  UNION ALL SELECT 'appian', 'Record Type',          'case_type',         'case_type',  'Appian Record = a data entity with a lifecycle. Maps to case_type + case_instances.',                          'CustomerRecord → case_type + case_instances table',   'close',   'Appian Record views map to Helix case detail panels'
  UNION ALL SELECT 'appian', 'Interface',            'form',              'form',       'Appian UI form definition. Maps to Helix FormDefinition JSON.',                                                  'LoanApplicationInterface → FormDefinition: loan_app',  'close',   'Appian SAIL expressions need re-expression'
  UNION ALL SELECT 'appian', 'Expression Rule',      'routing rule',      NULL,         'Reusable expression/formula. Maps to Helix routing rules or field calculated values.',                          'EligibilityRule → routing rule condition',            'close',   NULL
  UNION ALL SELECT 'appian', 'Decision',             'routing rule',      NULL,         'If/else decision node. Maps to Helix stage conditional routing.',                                               'ApprovalDecision → routing rule: if approved → done', 'close',   NULL
  UNION ALL SELECT 'appian', 'Constant',             'configuration',     NULL,         'Named constant value. Store in Helix case_type properties or tenant settings.',                                 'MAX_LOAN_AMOUNT → case_type property',                'close',   NULL
  UNION ALL SELECT 'appian', 'Site',                 'portal',            NULL,         'Appian customer-facing site. Maps to Helix portal.',                                                             'CustomerSite → portal: customer',                     'exact',   NULL
  UNION ALL SELECT 'appian', 'Group',                'access_group',      'access_group', 'Appian group for access control. Direct equivalent.',                                                         'LoanOfficersGroup → access_group: loan_officers',     'exact',   NULL
  UNION ALL SELECT 'appian', 'Role',                 'access_role',       NULL,         'Named privilege set. Maps to Helix access_role.',                                                                'ApproverRole → access_role: approver',                'exact',   NULL
  UNION ALL SELECT 'appian', 'Integration Object',   'HxConnect connector', 'connector', 'External system integration. Maps to HxConnect ConnectorProtocol.',                                           'SalesforceIntegration → HxConnect connector',         'close',   'Integration logic must be re-implemented'
  UNION ALL SELECT 'appian', 'Report',               'Analytics view',    NULL,         'Appian report/grid. Maps to Helix Analytics module or HxGraph query.',                                          'ClaimsReport → Analytics module + custom query',      'close',   NULL
  UNION ALL SELECT 'appian', 'Timer Event',          'sla_rule',          NULL,         'Time-based trigger. Maps to SLA rule with action on deadline.',                                                 'EscalationTimer 48h → sla_rule + escalation',         'close',   NULL
  UNION ALL SELECT 'servicenow', 'Workflow',           'case_type stages',  NULL,         'ServiceNow workflow = sequence of activities. Maps to Helix case_type stage sequence.',                  'IncidentWorkflow → case_type: incident stages',       'close',   NULL
  UNION ALL SELECT 'servicenow', 'Activity',           'step',              'step',       'Single unit of work in a workflow. Maps to a Helix step.',                                                  'ApprovalActivity → approval step',                    'close',   NULL
  UNION ALL SELECT 'servicenow', 'Approval',           'approval step',     'step',       'Approval request to a user or group. Direct equivalent.',                                                   'ManagerApproval → approval step',                     'exact',   NULL
  UNION ALL SELECT 'servicenow', 'Catalog Item',       'portal case_type',  'case_type',  'Service Catalog item = customer-submittable request. Maps to case_type with portal enabled.',              'LaptopRequest → portal-enabled case_type',            'exact',   NULL
  UNION ALL SELECT 'servicenow', 'Flow Designer Flow', 'case_type stages',  NULL,         'Visual flow builder. Maps to Helix stage + step definition.',                                               'OnboardingFlow → case_type: onboarding',              'close',   NULL
  UNION ALL SELECT 'servicenow', 'Assignment Group',   'access_group',      'access_group', 'Group that work is assigned to. Direct equivalent to Helix access_group.',                              'IT_Support → access_group: it_support',               'exact',   NULL
  UNION ALL SELECT 'servicenow', 'SLA Definition',     'sla_rule',          NULL,         'Response and resolution SLA timers. Direct equivalent.',                                                    'P1_SLA 4h response → sla_rule deadline 4h',           'exact',   NULL
  UNION ALL SELECT 'servicenow', 'Business Rule',      'automated step',    'step',       'Script triggered on record events. Maps to automated step with logic.',                                     'AssignmentRule → automated step on case create',      'partial', 'Script logic requires manual migration'
  UNION ALL SELECT 'servicenow', 'UI Action',          'form step action',  'step',       'Button on a form. Maps to a form step action (approve/reject/submit).',                                     'ResolveButton → form step action: resolve',           'close',   NULL
  UNION ALL SELECT 'servicenow', 'Transform Map',      'automated step',    'step',       'Data transformation script. Maps to automated step.',                                                       'ImportTransform → automated step: data_map',          'partial', 'Transform logic requires manual migration'
  UNION ALL SELECT 'servicenow', 'Scheduled Job',      'sla_rule escalation', NULL,       'Time-based recurring action. Maps to SLA escalation rule.',                                                 'DailyEscalation → sla_rule escalation action',        'close',   NULL
  UNION ALL SELECT 'servicenow', 'Knowledge Article',  'Knowledge Center',  NULL,         'Knowledge base article. Maps to HxGraph concept node + Knowledge Center entry.',                           'HowToArticle → knowledge_center entry / concept node', 'close',  NULL
) t
WHERE NOT EXISTS (SELECT 1 FROM bpm_concepts LIMIT 1);
