"""HxDraft P2 — natural language → a DRAFT login user ("create a user named X").

The riskiest draft kind, so the gate is the narrowest:

  * **The LLM never produces a password.** Normalization is schema-strict —
    username/email/display_name/roles only; any password-ish key in the output is
    dropped on the floor. Apply generates a strong temp password server-side,
    returns it exactly once, and sets ``password_change_required``.
  * **Closed role allowlist** — never admin, never superadmin, and not
    integration either (it can rotate connector credentials). Privilege grants are
    not draftable; an admin adds elevated roles manually afterwards.
  * Apply is **admin-only** (HxDraft's own check + the same posture as
    ``POST /auth/register``) and runs under the caller's token.
  * No fallback: identity is never guessed. AI down → honest UserDraftError.

Copyright (c) 2024-2025 HELIX Contributors
SPDX-License-Identifier: BSL-1.1
"""
from __future__ import annotations

import logging
import re
from typing import Any

from case_service.hxnexus.factory import generate_json as _ai_generate_json

logger = logging.getLogger(__name__)

MAX_PROMPT_CHARS = 4000
MAX_ROLES = 5

#: the ONLY roles a draft may propose — grants beyond these are added manually
ALLOWED_DRAFT_ROLES = {"viewer", "user", "agent", "designer", "manager"}

_USERNAME_RE = re.compile(r"^[a-z0-9][a-z0-9._-]{2,49}$")
_EMAIL_RE = re.compile(r"^[^@\s]+@[^@\s]+\.[^@\s]+$")

USER_PROMPT = """You are helping an administrator draft a login user account.
Convert the description into ONE user as JSON. Output ONLY valid JSON, no markdown
fences, no commentary. NEVER include a password — passwords are generated by the
platform, not by you.

JSON structure (use EXACTLY these keys):
{
  "username": "<lowercase, letters/digits/dot/dash/underscore, 3-50 chars>",
  "email": "<email address>",
  "display_name": "<full name or null>",
  "roles": ["viewer" and/or "user", "agent", "designer", "manager"]
}
Default roles to ["viewer"] when the description names none."""


class UserDraftError(Exception):
    """Draft generation failed in a way the card should state honestly."""


# ── validation gate ─────────────────────────────────────────────────────────────

def validate_user_draft(draft: dict[str, Any]) -> list[str]:
    """Every reason this draft must not become a card. Empty list = renderable."""
    errors: list[str] = []
    if not isinstance(draft, dict):
        return ["Draft is not an object"]

    username = str(draft.get("username") or "")
    if not _USERNAME_RE.fullmatch(username):
        errors.append(f"username {username!r} is invalid (lowercase letters, digits, "
                      f"'._-', 3-50 chars, must start alphanumeric)")

    email = str(draft.get("email") or "")
    if not _EMAIL_RE.fullmatch(email):
        errors.append(f"email {email!r} is not a valid address")

    roles = draft.get("roles")
    if not isinstance(roles, list) or not roles:
        errors.append("Draft needs at least one role")
        roles = []
    if len(roles) > MAX_ROLES:
        errors.append(f"Too many roles ({len(roles)} > {MAX_ROLES})")
    for role in roles:
        if role not in ALLOWED_DRAFT_ROLES:
            errors.append(f"Role {role!r} is outside the draftable allowlist "
                          f"{sorted(ALLOWED_DRAFT_ROLES)} — elevated roles are "
                          f"granted manually, never drafted")

    if any("password" in str(k).lower() for k in draft):
        errors.append("Drafts must never carry a password")

    return errors


# ── normalization (schema-strict: unknown keys — incl. passwords — never survive) ─

def normalize_user_draft(raw: dict[str, Any], *, prompt: str = "") -> dict[str, Any]:
    roles = [str(r).strip().lower() for r in (raw.get("roles") or [])
             if str(r).strip()][:MAX_ROLES + 1]
    provenance = (f'Drafted by HxNexus — "{prompt.strip()[:300]}"'
                  if prompt else "Drafted by HxNexus")
    return {
        "username": str(raw.get("username") or "").strip().lower()[:50],
        "email": str(raw.get("email") or "").strip()[:255],
        "display_name": (str(raw.get("display_name")).strip()[:100]
                         if raw.get("display_name") else None),
        "roles": roles or ["viewer"],
        "description": provenance,
    }


# ── generation ──────────────────────────────────────────────────────────────────

async def generate_user_draft(description: str) -> dict[str, Any]:
    """NL → normalized user draft + validation errors. Identity is never guessed."""
    description = (description or "").strip()
    if not description:
        raise UserDraftError("Describe the user you want drafted")
    if len(description) > MAX_PROMPT_CHARS:
        raise UserDraftError(f"Description too long (max {MAX_PROMPT_CHARS} characters)")

    raw = await _ai_generate_json(prompt=description, system=USER_PROMPT)
    if not raw or not isinstance(raw, dict):
        raise UserDraftError("AI backend unavailable — user accounts are never "
                             "drafted heuristically")

    draft = normalize_user_draft(raw, prompt=description)
    return {"source": "llm", "draft": draft, "errors": validate_user_draft(draft)}
