"""Auth provider Protocol — any identity/SSO provider."""
from __future__ import annotations
from typing import Any, Protocol, runtime_checkable
from pydantic import BaseModel


class UserInfo(BaseModel):
    user_id: str
    email: str
    name: str
    roles: list[str] = []
    groups: list[str] = []
    tenant_id: str | None = None


@runtime_checkable
class AuthProvider(Protocol):
    """Any auth/identity provider: Keycloak, Okta, Azure AD, etc."""

    def name(self) -> str: ...
    async def health_check(self) -> bool: ...
    async def initialize(self, config: dict[str, Any]) -> None: ...
    async def shutdown(self) -> None: ...

    async def validate_token(self, token: str) -> UserInfo | None: ...
    async def get_login_url(self, redirect_uri: str) -> str: ...
    async def exchange_code(self, code: str, redirect_uri: str) -> dict[str, str]: ...
    async def refresh_token(self, refresh_token: str) -> dict[str, str]: ...
    async def logout(self, token: str) -> None: ...
    async def get_user(self, user_id: str) -> UserInfo | None: ...
    async def list_roles(self) -> list[str]: ...
