"""LLM provider Protocol — any AI chat/completion API."""
from __future__ import annotations
from typing import Any, AsyncIterator, Protocol, runtime_checkable


@runtime_checkable
class LLMProvider(Protocol):
    """Any LLM API: OpenAI, Anthropic, Ollama, Gemini, etc."""

    def name(self) -> str: ...
    async def health_check(self) -> bool: ...
    async def initialize(self, config: dict[str, Any]) -> None: ...
    async def shutdown(self) -> None: ...

    async def complete(self, prompt: str, *, model: str,
                       max_tokens: int = 1000, temperature: float = 0.7,
                       system: str | None = None, **kwargs: Any) -> str: ...

    async def stream(self, prompt: str, *, model: str,
                     max_tokens: int = 1000, temperature: float = 0.7,
                     system: str | None = None, **kwargs: Any) -> AsyncIterator[str]: ...

    def list_models(self) -> list[dict[str, Any]]: ...
    def supports_function_calling(self) -> bool: ...
    def supports_vision(self) -> bool: ...
